__author__ = "John Mitromaras"
__author_email__ = "mitromarasg96@gmail.com"
__author_website__ = "https://github.com/Johnmaras"
__description__ = "Managing appointment scheduling with customizable slots, staff features, and conflict handling."
__package_name__ = "django-appointment-breformed"
__url__ = "https://github.com/Johnmaras/django-appointment"
__package_website__ = "https://giannismitromaras.pkgs.visualstudio.com/MyProject/_packaging/breformed/pypi/upload/"
__version__ = "3.3.5.48"
__test_version__ = False
